### ISSUE TITLE
使用mcs指令时报错

### ISSUE THREAD

**Issue by axlmly** [Kokoro-js/koishi-plugin-mc-server-status#9]
```
2024-03-20 14:40:05 [W] command mcs 
                        Error
                            at [cordis.invoke] (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\undios\lib\index.cjs:206:23)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async Proxy.<anonymous> (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\undios\lib\index.cjs:72:26)
                            at async Command.<anonymous> (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-mc-server-status\lib\commands\mcs.js:33:22)
                            at async Array.<anonymous> (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:1137:14)
                            at async Command.execute (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:1151:22)
                            at async C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:2174:22
                            at async Proxy.withScope (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:2077:22)
                            at async next (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:876:16)
                            at async next (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:876:16)
```
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz

Binaries:
    Node: 20.3.1
    Yarn: 4.1.0

Koishi:
    Core: 4.17.2
    Console: 5.26.5
    Koishi Desktop: 1.0.2

![432f16bf9d72ae.jpg](https://github.com/Kokoro-js/koishi-plugin-mc-server-status/assets/41771421/0901bf1b-2b86-439e-9a43-4e36bc44e23a)

![1f7fd3f64f0b809d.jpg](https://github.com/Kokoro-js/koishi-plugin-mc-server-status/assets/41771421/f105992f-0ca9-405a-b82c-abdbd5be6f8a)

**Comment by itzdrli** [comment]
鉴定为api炸了/跑路了，这段时间找个新的api
